import { OnInit, ElementRef, AfterViewInit, SimpleChanges } from '@angular/core';
export declare class ModalComponent implements OnInit, AfterViewInit {
    private elementRef;
    private $modal;
    private $el;
    private modalDialog;
    private isShown;
    private hasCustomHeader;
    private hasCustomFooter;
    private dragInit;
    private dragObj;
    private onHeaderMouseDown;
    private onDocumentMouseMove;
    private onDocumentMouseUp;
    readonly modalSize: string;
    private size;
    private width;
    private header;
    private animate;
    private okText;
    private cancelText;
    private allowDrag;
    private options;
    private onShown;
    private onHidden;
    private onCancel;
    private onOk;
    private shown;
    private shownChange;
    private modalHeader;
    private modalFooter;
    constructor(elementRef: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changesObj: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private configModalOptions();
    private configModalEvents();
    private initDrag();
    showModal(): void;
    hideModal(): void;
    onCancelClick(): void;
    onOkClick(): void;
    private initModalPosition();
}
